### ISSUE TITLE
Application getting Crashed

### ISSUE THREAD

**Issue by akapoor-ari** [VideoExpertsGroup/MediaPlayerSDK#4]
java.lang.UnsatisfiedLinkError: No implementation found for int veg.mediaplayer.sdk.Thumbnailer.nativeThumbnailerInit(veg.mediaplayer.sdk.Thumbnailer) (tried Java_veg_mediaplayer_sdk_Thumbnailer_nativeThumbnailerInit and Java_veg_mediaplayer_sdk_Thumbnailer_nativeThumbnailerInit__Lveg_mediaplayer_sdk_Thumbnailer_2)
            at veg.mediaplayer.sdk.Thumbnailer.nativeThumbnailerInit(Native Method)
            at veg.mediaplayer.sdk.ThumbnailerWorker.run(Thumbnailer.java:418)
            at java.lang.Thread.run(Thread.java:818)

**Comment by tahir9111** [comment]
Got crashed when running on Nexus 5x Android 7.1, using latest libraries mentioned above

 No implementation found for long veg.mediaplayer.sdk.MediaPlayer.nativePlayerInit(long[], veg.mediaplayer.sdk.MediaPlayer) (tried Java_veg_mediaplayer_sdk_MediaPlayer_nativePlayerInit and Java_veg_mediaplayer_sdk_MediaPlayer_nativePlayerInit___3JLveg_mediaplayer_sdk_MediaPlayer_2)
E/AndroidRuntime: FATAL EXCEPTION: MediaPlayerThread
                                                          Process: com.ritz, PID: 27552
                                                          java.lang.UnsatisfiedLinkError: No implementation found for long veg.mediaplayer.sdk.MediaPlayer.nativePlayerInit(long[], veg.mediaplayer.sdk.MediaPlayer) (tried Java_veg_mediaplayer_sdk_MediaPlayer_nativePlayerInit and Java_veg_mediaplayer_sdk_MediaPlayer_nativePlayerInit___3JLveg_mediaplayer_sdk_MediaPlayer_2)
                                                              at veg.mediaplayer.sdk.MediaPlayer.nativePlayerInit(Native Method)
                                                              at veg.mediaplayer.sdk.MediaPlayerWorker.run(MediaPlayer.java:4006)
                                                              at java.lang.Thread.run(Thread.java:761)
12-21 19:15:50.953 27552-27774/com.ritz E/art: No implementation found for long veg.mediaplayer.sdk.MediaPlayer.nativePlayerInit(long[], veg.mediaplayer.sdk.MediaPlayer) (tried Java_veg_mediaplayer_sdk_MediaPlayer_nativePlayerInit and Java_veg_mediaplayer_sdk_MediaPlayer_nativePlayerInit___3JLveg_mediaplayer_sdk_MediaPlayer_2)
/////////////////////////////////////

**Comment by ershovd** [comment]
@tahir9111 I have the similar issue. I am using the Xamarin.Android and have created custom binding from latests libs version. When trying to play RTSP video stream on Android 7.0 (API 24) the app got crashed with errors in native android libraries, with errors in log 
`[libc] Fatal signal 11 (SIGSEGV), code 1, fault addr 0x0 in tid 3860 (SDL_thread)`

I can provide full output and Android device log, if that helps.

@VideoExpertsGroup1 please advise. The related issues #9 is marked as closed, but apparently it is still exists. Can you confirm which commit fixed it? Thanks

**Comment by lexius** [comment]
The same problem

**Comment by NicolasGUILLOT** [comment]
Hi,
I have the same issue :
```
07-24 13:20:49.881 14432-14612/fr.ctcam.nexecur E/art: No implementation found for long veg.mediaplayer.sdk.MediaPlayer.nativePlayerInit(long[], veg.mediaplayer.sdk.MediaPlayer) (tried Java_veg_mediaplayer_sdk_MediaPlayer_nativePlayerInit and Java_veg_mediaplayer_sdk_MediaPlayer_nativePlayerInit___3JLveg_mediaplayer_sdk_MediaPlayer_2)
    
    --------- beginning of crash
07-24 13:20:50.023 14432-14612/fr.ctcam.nexecur E/AndroidRuntime: FATAL EXCEPTION: MediaPlayerThread
    Process: fr.ctcam.nexecur, PID: 14432
    java.lang.UnsatisfiedLinkError: No implementation found for long veg.mediaplayer.sdk.MediaPlayer.nativePlayerInit(long[], veg.mediaplayer.sdk.MediaPlayer) (tried Java_veg_mediaplayer_sdk_MediaPlayer_nativePlayerInit and Java_veg_mediaplayer_sdk_MediaPlayer_nativePlayerInit___3JLveg_mediaplayer_sdk_MediaPlayer_2)
        at veg.mediaplayer.sdk.MediaPlayer.nativePlayerInit(Native Method)
        at veg.mediaplayer.sdk.MediaPlayerWorker.run(MediaPlayer.java:4179)
        at java.lang.Thread.run(Thread.java:818)
```

@VideoExpertsGroup1  can you help us ? 
Thank you,
Nicolas

**Comment by bleikher** [comment]
Hi,

Please modify app/build.gradle
1. remove 
ndk {
            abiFilters 'x86', 'armeabi', 'armeabi-v7a'
        }

2. set latest library version
compile 'com.vxg.mediasdk:playersdk:2.0.55'

Regards,
Alexey Bleikher
Solution Architect | VXG
www.videoexpertsgroup.com

**Comment by NicolasGUILLOT** [comment]
Hi Alexey,
Thank you for your answer.
I will try this now !
Nicolas

Le mar. 24 juil. 2018 à 13:44, Alexey Bleikher <notifications@github.com> a
écrit :

**Comment by NicolasGUILLOT** [comment]
Hi Alexey,
I have try to implements com.vxg.mediasdk:playersdk:2.0.55, but I have a
"failed to resolve" issue.
I made a mistake ?
Thank you,
Nicolas

**Comment by bleikher** [comment]
Hi Nicolas,

Please check that root build.gradle has link to VXG repo:

allprojects {
    repositories {
        jcenter()
        maven {
            url 'http://exchange.videoexpertsgroup.com:8080/repository/internal/'
            name 'VXG'
        }
    }
}

Thanks,
Alexey Bleikher

**Comment by NicolasGUILLOT** [comment]
Alexey,
Now I have : 
```
Unable to resolve dependency for ':app@recette/compileClasspath': Could not resolve com.vxg.mediasdk:playersdk:2.0.55.
Open File
Show Details


Unable to resolve dependency for ':app@recetteUnitTest/compileClasspath': Could not resolve com.vxg.mediasdk:playersdk:2.0.55.
Open File
Show Details


Unable to resolve dependency for ':app@debug/compileClasspath': Could not resolve com.vxg.mediasdk:playersdk:2.0.55.
Open File
Show Details


Unable to resolve dependency for ':app@debugAndroidTest/compileClasspath': Could not resolve com.vxg.mediasdk:playersdk:2.0.55.
Open File
Show Details


Unable to resolve dependency for ':app@debugUnitTest/compileClasspath': Could not resolve com.vxg.mediasdk:playersdk:2.0.55.
Open File
Show Details


Unable to resolve dependency for ':app@prod/compileClasspath': Could not resolve com.vxg.mediasdk:playersdk:2.0.55.
Open File
Show Details


Unable to resolve dependency for ':app@prodUnitTest/compileClasspath': Could not resolve com.vxg.mediasdk:playersdk:2.0.55.
Open File
Show Details


Unable to resolve dependency for ':app@release/compileClasspath': Could not resolve com.vxg.mediasdk:playersdk:2.0.55.
Open File
Show Details


Unable to resolve dependency for ':app@releaseUnitTest/compileClasspath': Could not resolve com.vxg.mediasdk:playersdk:2.0.55.
Open File
Show Details
```

In my build.gradle, I have that code :
```
allprojects {
    repositories {

        maven {
            url 'http://exchange.videoexpertsgroup.com:8080/repository/internal/'
            name 'VXG'
        }
        maven { url 'https://maven.google.com' }
        google()
        jcenter()
      
    }
}
```
Thanks,
Nicolas

**Comment by bleikher** [comment]
Nicolas,

Have you done clean re-build:
(for Windows)
gradlew.bat clean
gradlew.bat assembleDebug

(for Linux)
./gradlew clean
./gradlew assembleDebug

?

Thanks,
Alexey

**Comment by NicolasGUILLOT** [comment]
Alexey,
Thanks for you answer !
The first one build successfully. (./gradlew clean)
The second (./gradlew assembleDebug) make this issue :

MacBook-Pro-de-Imanol:nexecur harinordoquy$ ./gradlew assembleDebug


*> Configure project :app*

WARNING: Configuration 'compile' is obsolete and has been replaced with
'implementation' and 'api'.

It will be removed at the end of 2018. For more information see:
http://d.android.com/r/tools/update-dependency-configurations.html



FAILURE: Build failed with an exception.


* What went wrong:

Could not resolve all files for configuration ':app:debugCompileClasspath'.

> Could not resolve com.vxg.mediasdk:playersdk:2.0.55.

  Required by:

      project :app

   > Could not resolve com.vxg.mediasdk:playersdk:2.0.55.

      > Could not get resource '
http://exchange.videoexpertsgroup.com:8080/repository/internal/com/vxg/mediasdk/playersdk/2.0.55/playersdk-2.0.55.pom
'.

         > Could not GET '
http://exchange.videoexpertsgroup.com:8080/repository/internal/com/vxg/mediasdk/playersdk/2.0.55/playersdk-2.0.55.pom
'.

            > Connect to exchange.videoexpertsgroup.com:8080 [
exchange.videoexpertsgroup.com/52.40.132.119] failed: Connection refused
(Connection refused)

   > Could not resolve com.vxg.mediasdk:playersdk:2.0.55.

      > Could not get resource '
https://maven.google.com/com/vxg/mediasdk/playersdk/2.0.55/playersdk-2.0.55.pom
'.

         > Could not GET '
https://maven.google.com/com/vxg/mediasdk/playersdk/2.0.55/playersdk-2.0.55.pom
'.

            > Connect to maven.google.com:443 [
maven.google.com/172.217.18.195,
maven.google.com/2a00:1450:4007:810:0:0:0:2003] failed: No route to host
(connect failed)


* Try:

Run with *--stacktrace* option to get the stack trace. Run with *--info* or
*--debug* option to get more log output. Run with *--scan* to get full
insights.


* Get more help at https://help.gradle.org


*BUILD FAILED* in 34s

1 actionable task: 1 executed

Thank you,
Nicolas

Le mar. 24 juil. 2018 à 15:14, Alexey Bleikher <notifications@github.com> a
écrit :

**Comment by bleikher** [comment]
Nicolas,

Please check internet connection at once for download the library.
Just try the link http://exchange.videoexpertsgroup.com:8080/repository/internal/com/vxg/mediasdk/playersdk/2.0.55/playersdk-2.0.55.pom
in browser.

Thanks,
Alexey

**Comment by NicolasGUILLOT** [comment]
We just move from an other office, I think 8080 port is certainly blocked.
I have to send a ticket to the network administrator.
Thank you to have take time to reply me.
Regards,
Nicolas

Le mar. 24 juil. 2018 à 15:30, Alexey Bleikher <notifications@github.com> a
écrit :

**Comment by NicolasGUILLOT** [comment]
Hi Alexey,
Thank you for you support, now that's working !
You add a VXG watermark on the streaming video ?
Thanks,
Nicolas

Le mer. 25 juil. 2018 à 08:27, Alexey Bleikher <notifications@github.com> a
écrit :

**Comment by bleikher** [comment]
Hi Nicolas,

VXG watermark is shown on the VXG player library trial version.
To disable watermark, please send email to support@videoexpertsgroup.com.

Regards,
Alexey
